apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mesoql
servers: 1
agents: 0
registries:
  create:
    name: mesoql-registry
    host: "0.0.0.0"
    hostPort: "5050"
ports:
  - port: 9200:9200
    nodeFilters:
      - loadbalancer
  - port: 11434:11434
    nodeFilters:
      - loadbalancer
